services:
  app:
    build: .
    image: misty-app-local
    ports:
      - "8080:8080"
    environment:
      APNS_DEVELOPMENT: "true"
      REFRESH_INTERVAL: ${REFRESH_INTERVAL:-}
      NOTIFY_INTERVAL: ${NOTIFY_INTERVAL:-}

  db:
    ports:
      - "5432:5432"

  caddy:
    profiles: [disabled]

secrets:
  cloudflare_api_token:
    file: /dev/null
  aop_ca_cert:
    file: /dev/null
