services:
  app:
    image: ghcr.io/jochemloedeman/misty:latest
  caddy:
    image: ghcr.io/jochemloedeman/misty/caddy:latest
    environment:
      DOMAIN: misty.jochemapps.com
    volumes:
      - caddy_data:/data
      - caddy_config:/config
