services:
  app:
    build: .
    image: misty-app-local

  caddy:
    build: ./caddy
    image: misty-caddy-local
    environment:
      DOMAIN: localhost
    ports:
      - "80:80"
    volumes:
      - ./caddy/conf/Caddyfile.local:/etc/caddy/Caddyfile:ro

secrets:
  cloudflare_api_token:
    file: /dev/null
