// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forecasts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listForecastsByMonitorIDAndHorizon = `-- name: ListForecastsByMonitorIDAndHorizon :many
SELECT
    forecast_at, monitor_id, temperature, dew_point, relative_humidity, wind_speed, visibility, weather_code
FROM
    forecasts
WHERE
    monitor_id = $1
    AND forecast_at >= $2
    AND forecast_at <= $3
ORDER BY
    forecast_at
`

type ListForecastsByMonitorIDAndHorizonParams struct {
	MonitorID pgtype.UUID
	From      pgtype.Timestamptz
	Until     pgtype.Timestamptz
}

func (q *Queries) ListForecastsByMonitorIDAndHorizon(ctx context.Context, arg ListForecastsByMonitorIDAndHorizonParams) ([]Forecast, error) {
	rows, err := q.db.Query(ctx, listForecastsByMonitorIDAndHorizon, arg.MonitorID, arg.From, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Forecast
	for rows.Next() {
		var i Forecast
		if err := rows.Scan(
			&i.ForecastAt,
			&i.MonitorID,
			&i.Temperature,
			&i.DewPoint,
			&i.RelativeHumidity,
			&i.WindSpeed,
			&i.Visibility,
			&i.WeatherCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertForecasts = `-- name: UpsertForecasts :exec
INSERT INTO
    forecasts (
        forecast_at,
        monitor_id,
        temperature,
        dew_point,
        relative_humidity,
        wind_speed,
        visibility,
        weather_code
    )
SELECT
    unnest($1::timestamptz[]),
    $2::uuid,
    unnest($3::float8[]),
    unnest($4::float8[]),
    unnest($5::float8[]),
    unnest($6::float8[]),
    unnest($7::float8[]),
    unnest($8::int[])
ON CONFLICT (forecast_at, monitor_id) DO
UPDATE
SET
    temperature = EXCLUDED.temperature,
    dew_point = EXCLUDED.dew_point,
    relative_humidity = EXCLUDED.relative_humidity,
    wind_speed = EXCLUDED.wind_speed,
    visibility = EXCLUDED.visibility,
    weather_code = EXCLUDED.weather_code
`

type UpsertForecastsParams struct {
	ForecastAt       []pgtype.Timestamptz
	MonitorID        pgtype.UUID
	Temperature      []float64
	DewPoint         []float64
	RelativeHumidity []float64
	WindSpeed        []float64
	Visibility       []float64
	WeatherCode      []int32
}

func (q *Queries) UpsertForecasts(ctx context.Context, arg UpsertForecastsParams) error {
	_, err := q.db.Exec(ctx, upsertForecasts,
		arg.ForecastAt,
		arg.MonitorID,
		arg.Temperature,
		arg.DewPoint,
		arg.RelativeHumidity,
		arg.WindSpeed,
		arg.Visibility,
		arg.WeatherCode,
	)
	return err
}
