// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationStatus string

const (
	NotificationStatusPending NotificationStatus = "pending"
	NotificationStatusSent    NotificationStatus = "sent"
	NotificationStatusExpired NotificationStatus = "expired"
)

func (e *NotificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationStatus(s)
	case string:
		*e = NotificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationStatus: %T", src)
	}
	return nil
}

type NullNotificationStatus struct {
	NotificationStatus NotificationStatus
	Valid              bool // Valid is true if NotificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationStatus), nil
}

type Forecast struct {
	ForecastAt       pgtype.Timestamptz
	MonitorID        pgtype.UUID
	Temperature      float64
	DewPoint         float64
	RelativeHumidity float64
	WindSpeed        float64
	Visibility       float64
	WeatherCode      int32
}

type Monitor struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	IsActive        bool
	LocationName    string
	Latitude        float64
	Longitude       float64
	RiskWindowStart pgtype.Timestamptz
	RiskWindowEnd   pgtype.Timestamptz
}

type Notification struct {
	ID           pgtype.UUID
	RecipientID  pgtype.UUID
	Message      string
	SentAt       pgtype.Timestamptz
	LocationName string
	FogStart     pgtype.Timestamptz
	FogEnd       pgtype.Timestamptz
	Status       NotificationStatus
}

type User struct {
	ID           pgtype.UUID
	PushToken    pgtype.Text
	RefreshToken string
}
