// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Forecast struct {
	ForecastAt       pgtype.Timestamptz
	MonitorID        pgtype.UUID
	Temperature      float64
	DewPoint         float64
	RelativeHumidity float64
	WindSpeed        float64
	Visibility       float64
	WeatherCode      int32
}

type Monitor struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	IsActive     bool
	LocationName string
	Latitude     float64
	Longitude    float64
	AlertStart   pgtype.Timestamptz
	AlertEnd     pgtype.Timestamptz
}

type Notification struct {
	ID          pgtype.UUID
	RecipientID pgtype.UUID
	Message     string
	SentAt      pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	PushToken    pgtype.Text
	RefreshToken string
}
