// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMonitorsByUser = `-- name: CountMonitorsByUser :one
SELECT
    count(*)
FROM
    monitors
WHERE
    user_id = $1
`

func (q *Queries) CountMonitorsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMonitorsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO
    monitors (
        id,
        user_id,
        is_active,
        location_name,
        latitude,
        longitude,
        alert_start,
        alert_end
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    ) RETURNING id, user_id, is_active, location_name, latitude, longitude, alert_start, alert_end
`

type CreateMonitorParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	IsActive     bool
	LocationName string
	Latitude     float64
	Longitude    float64
	AlertStart   pgtype.Timestamptz
	AlertEnd     pgtype.Timestamptz
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.ID,
		arg.UserID,
		arg.IsActive,
		arg.LocationName,
		arg.Latitude,
		arg.Longitude,
		arg.AlertStart,
		arg.AlertEnd,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsActive,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.AlertStart,
		&i.AlertEnd,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :execresult
DELETE FROM
    monitors
WHERE
    id = $1
    AND user_id = $2
`

type DeleteMonitorParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteMonitor, arg.ID, arg.UserID)
}

const getByMonitorID = `-- name: GetByMonitorID :one
SELECT
    id, user_id, is_active, location_name, latitude, longitude, alert_start, alert_end
FROM
    monitors
WHERE
    id = $1
    AND user_id = $2
`

type GetByMonitorIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetByMonitorID(ctx context.Context, arg GetByMonitorIDParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, getByMonitorID, arg.ID, arg.UserID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsActive,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.AlertStart,
		&i.AlertEnd,
	)
	return i, err
}

const listActiveMonitors = `-- name: ListActiveMonitors :many
SELECT
    id, user_id, is_active, location_name, latitude, longitude, alert_start, alert_end
FROM
    monitors
WHERE
    is_active = true
ORDER BY
    id
`

func (q *Queries) ListActiveMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listActiveMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IsActive,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.AlertStart,
			&i.AlertEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitors = `-- name: ListMonitors :many
SELECT
    id, user_id, is_active, location_name, latitude, longitude, alert_start, alert_end
FROM
    monitors
WHERE
    user_id = $1
ORDER BY
    id
`

func (q *Queries) ListMonitors(ctx context.Context, userID pgtype.UUID) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IsActive,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.AlertStart,
			&i.AlertEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE
    monitors
SET
    is_active = $1,
    alert_start = $2,
    alert_end = $3
WHERE
    id = $4
    AND user_id = $5 RETURNING id, user_id, is_active, location_name, latitude, longitude, alert_start, alert_end
`

type UpdateMonitorParams struct {
	IsActive   bool
	AlertStart pgtype.Timestamptz
	AlertEnd   pgtype.Timestamptz
	ID         pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.IsActive,
		arg.AlertStart,
		arg.AlertEnd,
		arg.ID,
		arg.UserID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsActive,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.AlertStart,
		&i.AlertEnd,
	)
	return i, err
}
