// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO
    notifications (
        id,
        recipient_id,
        message,
        sent_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4
    ) RETURNING id, recipient_id, message, sent_at
`

type CreateNotificationParams struct {
	ID          pgtype.UUID
	RecipientID pgtype.UUID
	Message     string
	SentAt      pgtype.Timestamptz
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.RecipientID,
		arg.Message,
		arg.SentAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Message,
		&i.SentAt,
	)
	return i, err
}

const listUnsentNotifications = `-- name: ListUnsentNotifications :many
SELECT
    id,
    recipient_id,
    message,
    sent_at
FROM
    notifications
WHERE
    sent_at IS NULL
ORDER BY
    id
`

func (q *Queries) ListUnsentNotifications(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnsentNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Message,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationSentAt = `-- name: UpdateNotificationSentAt :one
UPDATE
    notifications
SET
    sent_at = $1
WHERE
    id = $2 RETURNING id, recipient_id, message, sent_at
`

type UpdateNotificationSentAtParams struct {
	SentAt pgtype.Timestamptz
	ID     pgtype.UUID
}

func (q *Queries) UpdateNotificationSentAt(ctx context.Context, arg UpdateNotificationSentAtParams) (Notification, error) {
	row := q.db.QueryRow(ctx, updateNotificationSentAt, arg.SentAt, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Message,
		&i.SentAt,
	)
	return i, err
}
