// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO
    notifications (
        id,
        recipient_id,
        message,
        location_name,
        fog_start,
        fog_end,
        sent_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    ) RETURNING id, recipient_id, message, sent_at, location_name, fog_start, fog_end, status
`

type CreateNotificationParams struct {
	ID           pgtype.UUID
	RecipientID  pgtype.UUID
	Message      string
	LocationName string
	FogStart     pgtype.Timestamptz
	FogEnd       pgtype.Timestamptz
	SentAt       pgtype.Timestamptz
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.RecipientID,
		arg.Message,
		arg.LocationName,
		arg.FogStart,
		arg.FogEnd,
		arg.SentAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Message,
		&i.SentAt,
		&i.LocationName,
		&i.FogStart,
		&i.FogEnd,
		&i.Status,
	)
	return i, err
}

const getUnsentNotification = `-- name: GetUnsentNotification :one
SELECT
    id, recipient_id, message, sent_at, location_name, fog_start, fog_end, status
FROM
    notifications
WHERE
    id = $1
    AND status = 'pending'
`

func (q *Queries) GetUnsentNotification(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getUnsentNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Message,
		&i.SentAt,
		&i.LocationName,
		&i.FogStart,
		&i.FogEnd,
		&i.Status,
	)
	return i, err
}

const listUnsentNotifications = `-- name: ListUnsentNotifications :many
SELECT
    id, recipient_id, message, sent_at, location_name, fog_start, fog_end, status
FROM
    notifications
WHERE
    status = 'pending'
ORDER BY
    id
`

func (q *Queries) ListUnsentNotifications(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnsentNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Message,
			&i.SentAt,
			&i.LocationName,
			&i.FogStart,
			&i.FogEnd,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationExpired = `-- name: MarkNotificationExpired :one
UPDATE
    notifications
SET
    status = 'expired'
WHERE
    id = $1 RETURNING id, recipient_id, message, sent_at, location_name, fog_start, fog_end, status
`

func (q *Queries) MarkNotificationExpired(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationExpired, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Message,
		&i.SentAt,
		&i.LocationName,
		&i.FogStart,
		&i.FogEnd,
		&i.Status,
	)
	return i, err
}

const markNotificationSent = `-- name: MarkNotificationSent :one
UPDATE
    notifications
SET
    sent_at = $1,
    status = 'sent'
WHERE
    id = $2 RETURNING id, recipient_id, message, sent_at, location_name, fog_start, fog_end, status
`

type MarkNotificationSentParams struct {
	SentAt pgtype.Timestamptz
	ID     pgtype.UUID
}

func (q *Queries) MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationSent, arg.SentAt, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Message,
		&i.SentAt,
		&i.LocationName,
		&i.FogStart,
		&i.FogEnd,
		&i.Status,
	)
	return i, err
}

const markNotificationUndeliverable = `-- name: MarkNotificationUndeliverable :one
UPDATE
    notifications
SET
    status = 'undeliverable'
WHERE
    id = $1 RETURNING id, recipient_id, message, sent_at, location_name, fog_start, fog_end, status
`

func (q *Queries) MarkNotificationUndeliverable(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationUndeliverable, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Message,
		&i.SentAt,
		&i.LocationName,
		&i.FogStart,
		&i.FogEnd,
		&i.Status,
	)
	return i, err
}
