// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        id,
        push_token,
        refresh_token
    )
VALUES
    (
        $1,
        $2,
        $3
    ) RETURNING id, push_token, refresh_token
`

type CreateUserParams struct {
	ID           pgtype.UUID
	PushToken    pgtype.Text
	RefreshToken string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.PushToken, arg.RefreshToken)
	var i User
	err := row.Scan(&i.ID, &i.PushToken, &i.RefreshToken)
	return i, err
}

const ensureUser = `-- name: EnsureUser :exec
INSERT INTO
    users (
        id,
        push_token,
        refresh_token
    )
VALUES
    (
        $1,
        $2,
        $3
    ) ON CONFLICT (id) DO NOTHING
`

type EnsureUserParams struct {
	ID           pgtype.UUID
	PushToken    pgtype.Text
	RefreshToken string
}

func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) error {
	_, err := q.db.Exec(ctx, ensureUser, arg.ID, arg.PushToken, arg.RefreshToken)
	return err
}

const getByRefreshToken = `-- name: GetByRefreshToken :one
SELECT
    id,
    push_token,
    refresh_token
FROM
    users
WHERE
    refresh_token = $1
`

func (q *Queries) GetByRefreshToken(ctx context.Context, refreshToken string) (User, error) {
	row := q.db.QueryRow(ctx, getByRefreshToken, refreshToken)
	var i User
	err := row.Scan(&i.ID, &i.PushToken, &i.RefreshToken)
	return i, err
}

const getPushTokenByUserID = `-- name: GetPushTokenByUserID :one
SELECT
    push_token
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetPushTokenByUserID(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getPushTokenByUserID, id)
	var push_token pgtype.Text
	err := row.Scan(&push_token)
	return push_token, err
}
