// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertForecasts = `-- name: UpsertForecasts :batchexec
INSERT INTO
    forecasts (
        forecast_at,
        monitor_id,
        temperature,
        dew_point,
        relative_humidity,
        wind_speed,
        visibility
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    ) ON CONFLICT (monitor_id, forecast_at) DO
UPDATE
SET
    temperature = EXCLUDED.temperature,
    dew_point = EXCLUDED.dew_point,
    relative_humidity = EXCLUDED.relative_humidity,
    wind_speed = EXCLUDED.wind_speed,
    visibility = EXCLUDED.visibility
`

type UpsertForecastsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertForecastsParams struct {
	ForecastAt       pgtype.Timestamptz
	MonitorID        pgtype.UUID
	Temperature      float64
	DewPoint         float64
	RelativeHumidity float64
	WindSpeed        float64
	Visibility       int32
}

func (q *Queries) UpsertForecasts(ctx context.Context, arg []UpsertForecastsParams) *UpsertForecastsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ForecastAt,
			a.MonitorID,
			a.Temperature,
			a.DewPoint,
			a.RelativeHumidity,
			a.WindSpeed,
			a.Visibility,
		}
		batch.Queue(upsertForecasts, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertForecastsBatchResults{br, len(arg), false}
}

func (b *UpsertForecastsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertForecastsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
