// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forecasts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createForecast = `-- name: CreateForecast :one
INSERT INTO
    forecasts (
        forecast_at,
        monitor_id,
        temperature,
        dew_point,
        relative_humidity,
        wind_speed,
        visibility
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    ) RETURNING forecast_at, monitor_id, temperature, dew_point, relative_humidity, wind_speed, visibility
`

type CreateForecastParams struct {
	ForecastAt       pgtype.Timestamptz
	MonitorID        pgtype.UUID
	Temperature      float64
	DewPoint         float64
	RelativeHumidity float64
	WindSpeed        float64
	Visibility       int32
}

func (q *Queries) CreateForecast(ctx context.Context, arg CreateForecastParams) (Forecast, error) {
	row := q.db.QueryRow(ctx, createForecast,
		arg.ForecastAt,
		arg.MonitorID,
		arg.Temperature,
		arg.DewPoint,
		arg.RelativeHumidity,
		arg.WindSpeed,
		arg.Visibility,
	)
	var i Forecast
	err := row.Scan(
		&i.ForecastAt,
		&i.MonitorID,
		&i.Temperature,
		&i.DewPoint,
		&i.RelativeHumidity,
		&i.WindSpeed,
		&i.Visibility,
	)
	return i, err
}

const listForecastsByMonitorID = `-- name: ListForecastsByMonitorID :many
SELECT
    forecast_at, monitor_id, temperature, dew_point, relative_humidity, wind_speed, visibility
FROM
    forecasts
WHERE
    monitor_id = $1
ORDER BY
    forecast_at
`

func (q *Queries) ListForecastsByMonitorID(ctx context.Context, monitorID pgtype.UUID) ([]Forecast, error) {
	rows, err := q.db.Query(ctx, listForecastsByMonitorID, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Forecast
	for rows.Next() {
		var i Forecast
		if err := rows.Scan(
			&i.ForecastAt,
			&i.MonitorID,
			&i.Temperature,
			&i.DewPoint,
			&i.RelativeHumidity,
			&i.WindSpeed,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertForecast = `-- name: UpsertForecast :one
INSERT INTO
    forecasts (
        forecast_at,
        monitor_id,
        temperature,
        dew_point,
        relative_humidity,
        wind_speed,
        visibility
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    ) ON CONFLICT (forecast_at, monitor_id) DO
UPDATE
SET
    temperature = EXCLUDED.temperature,
    dew_point = EXCLUDED.dew_point,
    relative_humidity = EXCLUDED.relative_humidity,
    wind_speed = EXCLUDED.wind_speed,
    visibility = EXCLUDED.visibility RETURNING forecast_at, monitor_id, temperature, dew_point, relative_humidity, wind_speed, visibility
`

type UpsertForecastParams struct {
	ForecastAt       pgtype.Timestamptz
	MonitorID        pgtype.UUID
	Temperature      float64
	DewPoint         float64
	RelativeHumidity float64
	WindSpeed        float64
	Visibility       int32
}

func (q *Queries) UpsertForecast(ctx context.Context, arg UpsertForecastParams) (Forecast, error) {
	row := q.db.QueryRow(ctx, upsertForecast,
		arg.ForecastAt,
		arg.MonitorID,
		arg.Temperature,
		arg.DewPoint,
		arg.RelativeHumidity,
		arg.WindSpeed,
		arg.Visibility,
	)
	var i Forecast
	err := row.Scan(
		&i.ForecastAt,
		&i.MonitorID,
		&i.Temperature,
		&i.DewPoint,
		&i.RelativeHumidity,
		&i.WindSpeed,
		&i.Visibility,
	)
	return i, err
}
