// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO
    monitors (
        id,
        is_active,
        latitude,
        longitude,
        alert_start,
        alert_end
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    ) RETURNING id, is_active, latitude, longitude, alert_start, alert_end
`

type CreateMonitorParams struct {
	ID         pgtype.UUID
	IsActive   bool
	Latitude   float64
	Longitude  float64
	AlertStart pgtype.Timestamptz
	AlertEnd   pgtype.Timestamptz
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.ID,
		arg.IsActive,
		arg.Latitude,
		arg.Longitude,
		arg.AlertStart,
		arg.AlertEnd,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.Latitude,
		&i.Longitude,
		&i.AlertStart,
		&i.AlertEnd,
	)
	return i, err
}

const listActiveMonitors = `-- name: ListActiveMonitors :many
SELECT
    id, is_active, latitude, longitude, alert_start, alert_end
FROM
    monitors
WHERE
    is_active = true
ORDER BY
    id
`

func (q *Queries) ListActiveMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listActiveMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.IsActive,
			&i.Latitude,
			&i.Longitude,
			&i.AlertStart,
			&i.AlertEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitors = `-- name: ListMonitors :many
SELECT
    id, is_active, latitude, longitude, alert_start, alert_end
FROM
    monitors
ORDER BY
    id
`

func (q *Queries) ListMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.IsActive,
			&i.Latitude,
			&i.Longitude,
			&i.AlertStart,
			&i.AlertEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitorAlert = `-- name: UpdateMonitorAlert :one
UPDATE
    monitors
SET
    alert_start = $1,
    alert_end = $2
WHERE
    id = $3 RETURNING id, is_active, latitude, longitude, alert_start, alert_end
`

type UpdateMonitorAlertParams struct {
	AlertStart pgtype.Timestamptz
	AlertEnd   pgtype.Timestamptz
	ID         pgtype.UUID
}

func (q *Queries) UpdateMonitorAlert(ctx context.Context, arg UpdateMonitorAlertParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitorAlert, arg.AlertStart, arg.AlertEnd, arg.ID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.Latitude,
		&i.Longitude,
		&i.AlertStart,
		&i.AlertEnd,
	)
	return i, err
}
